version: '3'

services: 
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Mazdak@12345"
            MSSQL_PID: "Express"
        ports: 
            - "11433:1433"